name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, zip
      -
        name: Install dependencies
        run: composer install
      -
        name: Run PHPStan
        run: composer phpstan
      -
        name: Run PHP-CS-Fixer
        run: composer cs-fix
